### ISSUE TITLE
Placement conflicts w/ iOS 14 builtin controls

### ISSUE THREAD

**Issue by mickeyl** [futuretap/FTLinearActivityIndicator#13]
Thanks for this great activity indicator. Since iOS 14, the placement conflicts with the builtin indicators for microphone and camera usage though. Then again, the left side conflicts with the builtin 'Return to \<previous app\>' label.

It seems there is no good placement left, or is it? How about to the left and/or the right of the home indicator?

**Comment by jarrodparkes** [comment]
@mickeyl can you show an example (screenshot)?

**Comment by jarrodparkes** [comment]
<img width="818" alt="Screen Shot 2021-03-04 at 3 17 15 PM" src="https://user-images.githubusercontent.com/1331063/110031580-b712d680-7cfc-11eb-9b42-d6d25644aa6d.png">

SOURCE: https://support.apple.com/en-us/HT211876

**Comment by futuretap** [comment]
Probably the better alternative would be to (optionally) make a smaller version that can be put to the right of the cam/mic indicator. Haven't tested but can the cam and mic indicators both be visible?

**Comment by rrroyal** [comment]
Nope, only one indicator can be visible at the same time

**Comment by futuretap** [comment]
Should be fixed in 1.4. We now carefully adjust the placement of the control in the status bar depending on the device. Each device has different corner radii and notch width!
The cam/mic indicator should be kept clear. Unfortunately I wasn't able to test all device types in real life since the Simulator doesn't support the camera. Post screenshots with device type if there are any glitches.
